### ISSUE TITLE
Update Makefile

### ISSUE THREAD

**Issue by jslegendre** [bmcculley/macos-c-notifications#16]
Update Makefile to add these options:

`make static` : Only compile a static build of `libCUserNotification`
`make shared` : Only compile a shared library of `libCUserNotification`

**Comment by bmcculley** [comment]
Just submitted a pull request for this. I had to do a lot of reading for this, I think I finally grasped what was needed.

**Comment by jslegendre** [comment]
Hey, you did a great job with that.  Now you'll have this in your back pocket for future projects 👍

**Comment by bmcculley** [comment]
Thank you. Yes, it feels good to be learning new things!
