### ISSUE TITLE
Abstract away need for Obj-C types outside of library

### ISSUE THREAD

**Issue by jslegendre** [bmcculley/macos-c-notifications#17]
As I mentioned in a [past PR](https://github.com/bmcculley/macos-c-notifications/pull/10), I wanted to completely take away the need for someone using the library to need any Obj-C types. Currently in `notifier.c`, the only Obj-C type being used is `id`.  I have 2 ideas for this:

1. Create a `typedef struct` that will hold an `NSUserNotification` and all of its "accessories" i.e. title, subtitle, etc. 
Pro: Very concise and clear
Con: User must use a type we created, thus no longer using only native C types

2. Have the user create a variable of type `void *` that we will then cast as type `id` in the library.  
Pro: Keeps up using only C types
Con: Not really as clear and could foreseeably lead to confusing by the user

Thoughts?

**Comment by bmcculley** [comment]
I think I like the sound of the first choice better. I believe that making it clearer and easier to use is much better than sticking strictly with C types.

Which way are you leaning?

**Comment by jslegendre** [comment]
I was leaning towards the `typedef` option as well.  It really does make more sense.
