### ISSUE TITLE
Create setter functions for NSUserNotification

### ISSUE THREAD

**Issue by jslegendre** [bmcculley/macos-c-notifications#7]
Such as: `set_title`, `set_subtitle`, etc.

**Comment by bmcculley** [comment]
Oops, sorry I just messed around with this too. I should've marked it. Just pushed to setter_functions branch. Not sure if it's what you envisioned though.

**Comment by jslegendre** [comment]
Hey, no problem.  I just added you as a reviewer for my PR.  I kind of knocked out a couple of things in this one so I made a decent note in the PR explaining what I did and the rationale.
